index: # Je choisis le nom de ma route. /!\ Pas de doublon.
    path: / # Ma route
    controller: App\Controller\DefaultController::index

produit:
    path: /page/detail_prod
    controller: App\Controller\DefaultController::detail_prod

horaires:
    path: /page/horaires_cmd
    controller: App\Controller\DefaultController::horaires_cmd

restaurant:
    path: /restaurant
    controller: App\Controller\DefaultController::restaurant

panier:
    path: /panier
    controller: App\Controller\DefaultController::panier

paiement:
    path: /paiement
    controller: App\Controller\DefaultController::paiement
